(function(){"use strict";
const FYS=["FY26/27","FY27/28","FY28/29"],SCENARIOS=["Baseline","Budget","Plan"],MOVEMENTS=["Hire","Exit","Transfer In","Transfer Out"],COLORS={Baseline:"#9aa6a1",Budget:"#d19a32",Plan:"#517c91",ActualForecast:"#15805a"};
const state={monthly:[],movements:[],functions:new Set(),clusters:new Set(),countries:new Set(),movementTypes:new Set(MOVEMENTS),fy:"ALL",view:"summary",loaded:false,loading:false};
const el=id=>document.getElementById(id),safe=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c])),sum=(rows,key)=>rows.reduce((total,row)=>total+(Number(row[key])||0),0),monthKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`,fmtFte=v=>new Intl.NumberFormat("fr-FR",{maximumFractionDigits:0}).format(v||0),fmtMoney=v=>`${new Intl.NumberFormat("fr-FR",{maximumFractionDigits:1}).format((v||0)/1e6)} M€`,signed=(v,formatter)=>`${v>0?"+":""}${formatter(v)}`;
function parseDate(value){if(value instanceof Date)return new Date(value.getFullYear(),value.getMonth(),1);if(typeof value==="number"&&window.XLSX?.SSF){const p=XLSX.SSF.parse_date_code(value);if(p)return new Date(p.y,p.m-1,1)}const d=new Date(value);return new Date(d.getFullYear(),d.getMonth(),1)}
function rows(sheet){return XLSX.utils.sheet_to_json(sheet,{raw:true,defval:""})}
function normalizeMonthly(row){return{date:parseDate(row.Month),fy:row["Fiscal Year"],scenario:row.Scenario,entity:String(row["Legal Entity"]),region:row.Region,cluster:row.Cluster,country:row.Country,fn:row.Function,opening:+row["Opening FTE"],hire:+row["Hire FTE"],exit:+row["Exit FTE"],transferIn:+row["Transfer In FTE"],transferOut:+row["Transfer Out FTE"],movement:+row["Signed Movements FTE"],closing:+row["Closing FTE"],staff:+row["Staff Cost"],social:+row["Employer Social Charges"],total:+row["Total People Cost"],baselineTotal:+row["Baseline Total People Cost"],saving:+row["Monthly Savings vs Baseline"]}}
function normalizeMovement(row){return{date:parseDate(row.Month),fy:row["Fiscal Year"],scenario:row.Scenario,type:row["Movement Type"],fte:+row["Signed FTE"],entity:String(row["Legal Entity"]),region:row.Region,cluster:row.Cluster,country:row.Country,fn:row.Function,staff:+row["Monthly Staff Cost Impact"],social:+row["Employer Social Charges Impact"],total:+row["Total People Cost Impact"]}}
function allowed(row){return state.functions.has(row.fn)&&state.clusters.has(row.cluster)&&state.countries.has(row.country)&&(state.fy==="ALL"||row.fy===state.fy)}
function inScope(row){return state.functions.has(row.fn)&&state.clusters.has(row.cluster)&&state.countries.has(row.country)}
function compositeRows(){return state.monthly.filter(row=>allowed(row)&&(row.scenario==="Actual"||row.scenario==="Forecast"))}
function scenarioRows(scenario){return state.monthly.filter(row=>allowed(row)&&row.scenario===scenario)}
function compositeMovements(){return state.movements.filter(row=>allowed(row)&&state.movementTypes.has(row.type)&&(row.scenario==="Actual"||row.scenario==="Forecast"))}
function available(dimension){const source=state.monthly.filter(row=>row.scenario==="Baseline");if(dimension==="functions")return[...new Set(source.map(row=>row.fn))].sort();if(dimension==="clusters")return[...new Set(source.filter(row=>state.functions.has(row.fn)).map(row=>row.cluster))].sort();return[...new Set(source.filter(row=>state.functions.has(row.fn)&&state.clusters.has(row.cluster)).map(row=>row.country))].sort()}
function filterList(id,values,selected,dimension){el(id).innerHTML=values.map(value=>`<label class="check-item"><input type="checkbox" data-od-dimension="${dimension}" value="${safe(value)}" ${selected.has(value)?"checked":""}><span class="filter-value">${safe(value)}</span></label>`).join("")}
function renderFilters(){const functions=available("functions"),clusters=available("clusters"),countries=available("countries");state.functions=new Set([...state.functions].filter(value=>functions.includes(value)));state.clusters=new Set([...state.clusters].filter(value=>clusters.includes(value)));state.countries=new Set([...state.countries].filter(value=>countries.includes(value)));filterList("odFunctionFilters",functions,state.functions,"functions");filterList("odClusterFilters",clusters,state.clusters,"clusters");filterList("odCountryFilters",countries,state.countries,"countries");filterList("odMovementFilters",MOVEMENTS,state.movementTypes,"movementTypes");el("odScopeSummary").textContent=`${state.functions.size===functions.length?"Toutes fonctions":[...state.functions].join(", ")} · ${state.clusters.size===clusters.length?"Tous clusters":state.clusters.size+" cluster(s)"} · ${state.countries.size===countries.length?"Tous pays":state.countries.size+" pays"}`}
function byMonth(rows){const map=new Map();for(const row of rows){const key=monthKey(row.date),item=map.get(key)||{date:row.date,fy:row.fy,opening:0,closing:0,staff:0,social:0,total:0,saving:0,hire:0,exit:0,transferIn:0,transferOut:0,movement:0};item.opening+=row.opening;item.closing+=row.closing;item.staff+=row.staff;item.social+=row.social;item.total+=row.total;item.saving+=row.saving;item.hire+=row.hire;item.exit+=row.exit;item.transferIn+=row.transferIn;item.transferOut+=row.transferOut;item.movement+=row.movement;map.set(key,item)}return[...map.values()].sort((a,b)=>a.date-b.date)}
function seriesData(){return{Baseline:byMonth(scenarioRows("Baseline")),Budget:byMonth(scenarioRows("Budget")),Plan:byMonth(scenarioRows("Plan")),ActualForecast:byMonth(compositeRows())}}
function latest(rows){return rows.length?rows[rows.length-1]:null}
function currentActual(){return latest(byMonth(state.monthly.filter(row=>inScope(row)&&row.scenario==="Actual")))}
function endForecast(){return latest(byMonth(compositeRows()))}
function endPlan(){return latest(byMonth(scenarioRows("Plan")))}
function baseline(){return byMonth(scenarioRows("Baseline"))[0]||null}
function summary(){const base=baseline(),actual=currentActual(),forecast=endForecast(),plan=endPlan(),combined=compositeRows(),baselineRows=state.monthly.filter(row=>allowed(row)&&row.scenario==="Baseline"),staffOnly=sum(baselineRows,"staff")-sum(combined,"staff"),socialOnly=sum(baselineRows,"social")-sum(combined,"social"),net=staffOnly+socialOnly,gap=(forecast?.closing||0)-(plan?.closing||0);return{base,actual,forecast,plan,staffOnly,socialOnly,net,gap}}
function card(label,value,foot,tone="neutral"){return`<article class="od-metric-card ${tone}"><span>${label}</span><strong>${value}</strong><small>${foot}</small></article>`}
function renderSummaryCards(){const s=summary(),period=state.fy==="ALL"?"Cumul programme":`Impact ${state.fy}`,forecastFoot=state.fy==="ALL"?"Juin 2029":`Fin ${state.fy}`;el("odSummaryCards").innerHTML=[card("ETP baseline",fmtFte(s.base?.closing),"Juin 2026 · baseline figée"),card("ETP actuel",fmtFte(s.actual?.closing),"Arrêté août 2026","primary"),card("ETP forecast",fmtFte(s.forecast?.closing),forecastFoot),card("Écart ETP au plan",signed(s.gap,fmtFte),"Forecast moins plan",s.gap<=0?"good":"bad"),card("Économies staff costs",fmtMoney(s.staffOnly),period,s.staffOnly>=0?"good":"bad"),card("Économies charges sociales",fmtMoney(s.socialOnly),period,s.socialOnly>=0?"good":"bad"),card("Économies nettes",fmtMoney(s.net),period,s.net>=0?"good":"bad")].join("")}
function ticks(min,max,count=5){return Array.from({length:count},(_,i)=>min+(max-min)*i/(count-1))}
function lineChart(series,key,formatter,options={}){const entries=Object.entries(series).filter(([,rows])=>rows.length);if(!entries.length)return`<div class="empty-chart">Aucune donnée pour ce périmètre.</div>`;const all=entries.flatMap(([,rows])=>rows.map(row=>row[key])),min=Math.min(...all),max=Math.max(...all),pad=(max-min||1)*.12,W=900,H=300,L=62,R=18,T=22,B=40,x=index=>L+index/(Math.max(1,entries[0][1].length-1))*(W-L-R),y=value=>T+(max+pad-value)/(max-min+2*pad)*(H-T-B),grid=ticks(min-pad,max+pad);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${safe(options.label||"Trajectoire")}">${grid.map(v=>`<line class="grid-line" x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}"></line><text class="axis-label" x="${L-8}" y="${y(v)+3}" text-anchor="end">${safe(formatter(v))}</text>`).join("")}`;for(const[name,rows]of entries){const points=rows.map((row,index)=>`${x(index)},${y(row[key])}`).join(" "),dash=name==="Baseline"?"6 5":name==="Budget"?"3 4":"",width=name==="ActualForecast"?3:2;svg+=`<polyline fill="none" stroke="${COLORS[name]}" stroke-width="${width}" stroke-dasharray="${dash}" points="${points}"></polyline>`}const labels=entries[0][1];[0,11,23,35].filter(i=>labels[i]).forEach(i=>svg+=`<text class="axis-label" x="${x(i)}" y="${H-14}" text-anchor="middle">${safe(labels[i].fy)}</text>`);if(options.cutoff&&labels[1]){const i=1;svg+=`<line x1="${x(i)}" x2="${x(i)}" y1="${T}" y2="${H-B}" stroke="#64736d" stroke-dasharray="3 3"></line><text class="axis-label" x="${x(i)+5}" y="${T+10}">Août 2026</text>`}return svg+`</svg>`}
function legend(){return Object.entries({Baseline:"Baseline",Budget:"Budget",Plan:"Plan",ActualForecast:"Actual + forecast"}).map(([key,label])=>`<span><i style="background:${COLORS[key]}"></i>${label}</span>`).join("")}
function cumulativeChart(){const rows=byMonth(compositeRows()),W=560,H=300,L=65,R=18,T=24,B=42,values=[];let running=0;rows.forEach(row=>{running+=row.saving;values.push(running)});if(!rows.length)return`<div class="empty-chart">Aucune donnée pour ce périmètre.</div>`;const min=Math.min(0,...values),max=Math.max(0,...values),pad=(max-min||1)*.12,x=i=>L+i/Math.max(1,rows.length-1)*(W-L-R),y=v=>T+(max+pad-v)/(max-min+2*pad)*(H-T-B),zero=y(0),points=values.map((v,i)=>`${x(i)},${y(v)}`).join(" ");return`<svg viewBox="0 0 ${W} ${H}"><line class="zero-line" x1="${L}" x2="${W-R}" y1="${zero}" y2="${zero}"></line><polygon points="${x(0)},${zero} ${points} ${x(values.length-1)},${zero}" fill="rgba(21,128,90,.13)"></polygon><polyline points="${points}" fill="none" stroke="${COLORS.ActualForecast}" stroke-width="3"></polyline><text class="od-big-chart-value" x="${W-R}" y="${Math.max(T+16,y(values.at(-1))-10)}" text-anchor="end">${safe(fmtMoney(values.at(-1)))}</text>${[0,11,23,35].filter(i=>rows[i]).map(i=>`<text class="axis-label" x="${x(i)}" y="${H-14}" text-anchor="middle">${safe(rows[i].fy)}</text>`).join("")}</svg>`}
function annual(){const composite=byMonth(compositeRows()),plan=byMonth(scenarioRows("Plan")),budget=byMonth(scenarioRows("Budget")),years=state.fy==="ALL"?FYS:[state.fy];return years.map(fy=>{const c=composite.filter(row=>row.date&&row.fy===fy),p=plan.filter(row=>row.fy===fy),b=budget.filter(row=>row.fy===fy),cSave=sum(c,"saving"),pSave=sum(p,"saving"),bSave=sum(b,"saving"),fte=(c.at(-1)?.closing||0)-(c[0]?.opening||0);return`<article class="od-annual-card"><div><span>${fy}</span><strong class="${cSave>=0?"value-good":"value-bad"}">${fmtMoney(cSave)}</strong><small>économie actual + forecast</small></div><dl><dt>Impact ETP</dt><dd>${signed(fte,fmtFte)}</dd><dt>Plan</dt><dd>${fmtMoney(pSave)}</dd><dt>Budget</dt><dd>${fmtMoney(bSave)}</dd></dl></article>`}).join("")}
function movementTotals(){const rows=compositeMovements(),totals={Hire:0,Exit:0,"Transfer In":0,"Transfer Out":0};rows.forEach(row=>totals[row.type]+=Math.abs(row.fte));return totals}
function waterfall(){const totals=movementTotals(),monthly=byMonth(compositeRows()),start=monthly[0]?.opening||0,steps=[{label:"ETP initial",delta:0,total:start,type:"total"},{label:"Recrutements",delta:totals.Hire},{label:"Départs",delta:-totals.Exit},{label:"Transferts entrants",delta:totals["Transfer In"]},{label:"Transferts sortants",delta:-totals["Transfer Out"]}],W=880,H=310,L=25,R=20,T=30,B=65,barW=110,gap=32,max=Math.max(start,...steps.slice(1).reduce((a,s)=>{a.push((a.at(-1)||start)+s.delta);return a},[]))*1.1,y=v=>T+(max-v)/Math.max(max,1)*(H-T-B);let running=start;const bars=[{...steps[0],from:0,to:start}];steps.slice(1).forEach(step=>{const next=running+step.delta;bars.push({...step,from:running,to:next});running=next});bars.push({label:"ETP après sélection",from:0,to:running,type:"total"});return`<svg viewBox="0 0 ${W} ${H}">${bars.map((bar,i)=>{const x=L+i*(barW+gap),top=y(Math.max(bar.from,bar.to)),height=Math.max(3,Math.abs(y(bar.from)-y(bar.to))),color=bar.type==="total"?"#07533d":bar.to>=bar.from?"#35a36f":"#c94c52";return`<rect x="${x}" y="${top}" width="${barW}" height="${height}" rx="4" fill="${color}"></rect><text class="od-waterfall-value" x="${x+barW/2}" y="${top-7}" text-anchor="middle">${bar.type==="total"?fmtFte(bar.to):signed(bar.delta,fmtFte)}</text><text class="od-waterfall-label" x="${x+barW/2}" y="${H-34}" text-anchor="middle">${safe(bar.label)}</text>`}).join("")}</svg>`}
function movementChart(){const events=compositeMovements(),map=new Map();for(const event of events){const key=monthKey(event.date),row=map.get(key)||{date:event.date,fy:event.fy,hire:0,exit:0,transferIn:0,transferOut:0};if(event.type==="Hire")row.hire+=Math.abs(event.fte);if(event.type==="Exit")row.exit+=Math.abs(event.fte);if(event.type==="Transfer In")row.transferIn+=Math.abs(event.fte);if(event.type==="Transfer Out")row.transferOut+=Math.abs(event.fte);map.set(key,row)}const rows=[...map.values()].sort((a,b)=>a.date-b.date);if(!rows.length)return`<div class="empty-chart">Aucun mouvement sélectionné.</div>`;const W=900,H=320,L=56,R=22,T=22,B=45,max=Math.max(...rows.flatMap(row=>[row.hire,row.exit,row.transferIn,row.transferOut]),1),x=i=>L+i/rows.length*(W-L-R),group=(W-L-R)/rows.length,scale=(H-T-B)/(max*2.4),colors={hire:"#35a36f",exit:"#c94c52",transferIn:"#517c91",transferOut:"#d19a32"};return`<svg viewBox="0 0 ${W} ${H}"><line class="zero-line" x1="${L}" x2="${W-R}" y1="${H/2}" y2="${H/2}"></line>${rows.map((row,i)=>{const net=row.hire-row.exit+row.transferIn-row.transferOut,bar=Math.max(3,group*.14),base=x(i);return`<rect x="${base}" y="${H/2-row.hire*scale}" width="${bar}" height="${row.hire*scale}" fill="${colors.hire}"></rect><rect x="${base+bar}" y="${H/2}" width="${bar}" height="${row.exit*scale}" fill="${colors.exit}"></rect><rect x="${base+bar*2}" y="${H/2-row.transferIn*scale}" width="${bar}" height="${row.transferIn*scale}" fill="${colors.transferIn}"></rect><rect x="${base+bar*3}" y="${H/2}" width="${bar}" height="${row.transferOut*scale}" fill="${colors.transferOut}"></rect><circle cx="${base+bar*2}" cy="${H/2-net*scale}" r="3" fill="#17231f"></circle>`}).join("")}${[0,11,23,35].filter(i=>rows[i]).map(i=>`<text class="axis-label" x="${x(i)}" y="${H-13}">${safe(rows[i].fy)}</text>`).join("")}</svg>`}
function savingsChart(){const composite=seriesData().ActualForecast;if(!composite.length)return`<div class="empty-chart">Aucune donnée pour ce périmètre.</div>`;const W=900,H=300,L=62,R=58,T=22,B=40,x=i=>L+i/Math.max(1,composite.length-1)*(W-L-R),monthlyMax=Math.max(...composite.map(row=>Math.abs(row.saving)),1),monthlyY=v=>H/2-v/monthlyMax*(H/2-T-18),cumulative=[];let running=0;composite.forEach(row=>{running+=row.saving;cumulative.push(running)});const cumMin=Math.min(0,...cumulative),cumMax=Math.max(0,...cumulative),cumPad=(cumMax-cumMin||1)*.1,cumY=v=>T+(cumMax+cumPad-v)/(cumMax-cumMin+2*cumPad)*(H-T-B),points=cumulative.map((value,i)=>`${x(i)},${cumY(value)}`).join(" ");return`<svg viewBox="0 0 ${W} ${H}"><line class="zero-line" x1="${L}" x2="${W-R}" y1="${H/2}" y2="${H/2}"></line>${composite.map((row,i)=>`<rect x="${x(i)-5}" y="${Math.min(H/2,monthlyY(row.saving))}" width="10" height="${Math.abs(monthlyY(row.saving)-H/2)}" fill="${row.saving>=0?"#35a36f":"#c94c52"}"></rect>`).join("")}<polyline points="${points}" fill="none" stroke="#07533d" stroke-width="2.5"></polyline><text class="axis-label" x="${W-R+5}" y="${cumY(cumulative.at(-1))+3}">${safe(fmtMoney(cumulative.at(-1)))}</text></svg>`}
function detailRows(){const composite=compositeRows(),plan=scenarioRows("Plan"),base=scenarioRows("Baseline"),groups=new Map();for(const row of composite){const key=[row.fn,row.cluster,row.country].join("|"),g=groups.get(key)||{fn:row.fn,cluster:row.cluster,country:row.country,hire:0,exit:0,transferIn:0,transferOut:0,staff:0,social:0,saving:0};g.hire+=state.movementTypes.has("Hire")?row.hire:0;g.exit+=state.movementTypes.has("Exit")?row.exit:0;g.transferIn+=state.movementTypes.has("Transfer In")?row.transferIn:0;g.transferOut+=state.movementTypes.has("Transfer Out")?row.transferOut:0;g.staff+=row.staff;g.social+=row.social;g.saving+=row.saving;groups.set(key,g)}return[...groups.values()].map(g=>{const scope=row=>row.fn===g.fn&&row.cluster===g.cluster&&row.country===g.country,b=byMonth(base.filter(scope)),c=byMonth(composite.filter(scope)),p=byMonth(plan.filter(scope)),baseFte=b[0]?.closing||0,forecast=c.at(-1)?.closing||0,planFte=p.at(-1)?.closing||0,transfer=g.transferIn-g.transferOut,net=g.hire-g.exit+transfer;return{...g,baseFte,forecast,planFte,transfer,net,gap:forecast-planFte}}).sort((a,b)=>a.fn.localeCompare(b.fn)||a.cluster.localeCompare(b.cluster)||a.country.localeCompare(b.country))}
function renderDetail(){el("odDetailBody").innerHTML=detailRows().map(row=>`<tr><td><strong>${safe(row.fn)}</strong><small>${safe(row.cluster)} · ${safe(row.country)}</small></td><td class="numeric">${fmtFte(row.baseFte)}</td><td class="numeric value-good">+${fmtFte(row.hire)}</td><td class="numeric value-bad">−${fmtFte(row.exit)}</td><td class="numeric">${signed(row.transfer,fmtFte)}</td><td class="numeric">${signed(row.net,fmtFte)}</td><td class="numeric">${fmtFte(row.forecast)}</td><td class="numeric ${row.gap<=0?"value-good":"value-bad"}">${signed(row.gap,fmtFte)}</td><td class="numeric">${fmtMoney(row.staff)}</td><td class="numeric">${fmtMoney(row.social)}</td><td class="numeric ${row.saving>=0?"value-good":"value-bad"}">${fmtMoney(row.saving)}</td></tr>`).join("")}
function render(){renderFilters();renderSummaryCards();const series=seriesData(),leg=legend(),showCutoff=state.fy==="ALL"||state.fy==="FY26/27";el("odFteLegend").innerHTML=leg;el("odFteLegendDetail").innerHTML=leg;el("odFteChart").innerHTML=lineChart(series,"closing",fmtFte,{cutoff:showCutoff,label:"Trajectoire ETP"});el("odFteChartDetail").innerHTML=el("odFteChart").innerHTML;el("odCumulativeChart").innerHTML=cumulativeChart();el("odAnnualCards").innerHTML=annual();el("odStaffChart").innerHTML=lineChart(series,"staff",fmtMoney,{cutoff:showCutoff});el("odSocialChart").innerHTML=lineChart(series,"social",fmtMoney,{cutoff:showCutoff});el("odSavingsChart").innerHTML=savingsChart();el("odWaterfallChart").innerHTML=waterfall();el("odMovementChart").innerHTML=movementChart();el("odWaterfallPeriod").textContent=state.fy==="ALL"?"FY26/27 à FY28/29":state.fy;renderDetail()}
function setModule(name){document.querySelectorAll("[data-module]").forEach(button=>{const active=button.dataset.module===name;button.classList.toggle("active",active);button.setAttribute("aria-selected",active)});el("costModule").classList.toggle("hidden",name!=="costs");el("kpiModule").classList.toggle("hidden",name!=="kpis");el("odModule").classList.toggle("hidden",name!=="od");el("costImportButton").classList.toggle("hidden",name!=="costs");el("dataStatus").classList.toggle("hidden",name!=="costs")}
async function load(){if(state.loaded||state.loading)return;state.loading=true;try{const response=await fetch("./Gooduelle_Performance_Demo.xlsx"),buffer=await response.arrayBuffer(),book=XLSX.read(buffer,{type:"array",cellDates:true});state.monthly=rows(book.Sheets.OD_Monthly).map(normalizeMonthly);state.movements=rows(book.Sheets.OD_Movements).map(normalizeMovement);state.functions=new Set([...new Set(state.monthly.map(row=>row.fn))]);state.clusters=new Set([...new Set(state.monthly.map(row=>row.cluster))]);state.countries=new Set([...new Set(state.monthly.map(row=>row.country))]);state.loaded=true;el("odLoading").classList.add("hidden");el("odContent").classList.remove("hidden");render()}finally{state.loading=false}}
document.querySelector(".module-nav").addEventListener("click",event=>{const button=event.target.closest("[data-module]");if(!button)return;setModule(button.dataset.module);if(button.dataset.module==="od")load().catch(error=>{el("odLoading").textContent=`Impossible de charger les données OD : ${error.message}`;el("odLoading").classList.add("error")})});
el("odViewSelector").addEventListener("click",event=>{const button=event.target.closest("[data-od-view]");if(!button)return;state.view=button.dataset.odView;document.querySelectorAll("[data-od-view]").forEach(item=>item.classList.toggle("active",item===button));document.querySelectorAll("[data-od-panel]").forEach(panel=>panel.classList.toggle("hidden",panel.dataset.odPanel!==state.view))});
el("odFiscalYear").addEventListener("change",event=>{state.fy=event.target.value;render()});
el("odModule").addEventListener("change",event=>{const input=event.target.closest("input[data-od-dimension]");if(!input)return;const set=state[input.dataset.odDimension];input.checked?set.add(input.value):set.delete(input.value);if(input.dataset.odDimension==="functions"){state.clusters=new Set(available("clusters"));state.countries=new Set(available("countries"))}else if(input.dataset.odDimension==="clusters")state.countries=new Set(available("countries"));render()});
el("odModule").addEventListener("click",event=>{const all=event.target.closest("[data-od-all]");if(!all)return;state[all.dataset.odAll]=new Set(all.dataset.odAll==="movementTypes"?MOVEMENTS:available(all.dataset.odAll));if(all.dataset.odAll==="functions"){state.clusters=new Set(available("clusters"));state.countries=new Set(available("countries"))}render()});
el("odReset").addEventListener("click",()=>{state.functions=new Set(available("functions"));state.clusters=new Set(available("clusters"));state.countries=new Set(available("countries"));state.movementTypes=new Set(MOVEMENTS);state.fy="ALL";el("odFiscalYear").value="ALL";render()});
})();
