const fs=require("fs"),XLSX=require("./xlsx.full.min.js"),w=XLSX.read(fs.readFileSync("Gooduelle_Performance_Demo.xlsx"),{type:"buffer",cellDates:true}),rows=n=>XLSX.utils.sheet_to_json(w.Sheets[n],{header:1,raw:true,defval:""});
const required=["Mapping","Cost Baseline","Lever BCase - Updated","Budget FY26-27","Monthly_Data","KPI_Catalog","KPI_History","OD_Movements","OD_Monthly","Data Dictionary","Generation Log"];for(const n of required)if(!w.Sheets[n])throw Error(`Missing ${n}`);
const mapping=rows("Mapping"),baseline=rows("Cost Baseline"),budget=rows("Budget FY26-27"),monthly=rows("Monthly_Data"),catalog=rows("KPI_Catalog"),history=rows("KPI_History"),odMovements=rows("OD_Movements"),odMonthly=rows("OD_Monthly"),dictionary=rows("Data Dictionary"),log=rows("Generation Log");
const functions=["D&T","Finance","HR","Supply","Marketing","Sales"],entities=mapping.slice(1).map(r=>r[0]),categories=["Staff Cost - Indirect","Staff Cost - SG&A","Staff Cost - SG&A or Indirect","External Personnel Costs","IT Costs","Outside Consulting, Fees","Other Costs"];
const expected=entities.length*functions.length*categories.length;if(budget.length-6!==expected)throw Error(`Budget coverage ${budget.length-6}/${expected}`);for(const entity of entities)for(const fn of functions)for(const cat of categories)if(!budget.slice(6).some(r=>r[3]===entity&&r[1]===fn&&r[8]===cat))throw Error(`Missing budget ${entity}/${fn}/${cat}`);
for(const r of baseline.slice(2))for(const v of r.slice(4,10))if(Number(v)<0)throw Error("Negative baseline");
const monthlyTotals=new Map();for(const r of monthly.slice(1)){const key=[r[4],r[8],r[9]].join("|");monthlyTotals.set(key,(monthlyTotals.get(key)||0)+Number(r[11]))}for(const r of baseline.slice(2)){functions.forEach((fn,i)=>{const key=[r[0],fn,r[3]].join("|");if(Math.abs((monthlyTotals.get(key)||0)-Number(r[4+i]))>.01)throw Error(`Monthly reconciliation ${key}`)})}
if(catalog.length<13||history.length<500||log.length<100)throw Error("Traceability datasets too small");
const movementHeaders=odMovements[0],monthlyHeaders=odMonthly[0],requiredMovementHeaders=["Movement Type","Exit Subtype","Signed FTE","Recurring Staff Cost Impact","Recurring Employer Social Charges Impact","Transformation Social Cost (ENR)","Recurring Total People Cost Impact","Total Cash Cost Impact Including ENR"],requiredMonthlyHeaders=["Recurring Staff Cost","Recurring Employer Social Charges","Transformation Social Cost (ENR)","Recurring Total People Cost","Total Cash Cost Including ENR","Recurring Savings vs Baseline","Net Savings After ENR","Cumulative Recurring Savings","Cumulative Net Savings"];
for(const header of requiredMovementHeaders)if(!movementHeaders.includes(header))throw Error(`Missing OD movement column ${header}`);for(const header of requiredMonthlyHeaders)if(!monthlyHeaders.includes(header))throw Error(`Missing OD monthly column ${header}`);
const mi=Object.fromEntries(movementHeaders.map((header,index)=>[header,index])),oi=Object.fromEntries(monthlyHeaders.map((header,index)=>[header,index])),monthKey=value=>{const date=new Date(value);return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`},odFiscalYears=new Set(["FY26/27","FY27/28","FY28/29"]),odScenarios=new Set(["Baseline","Budget","Plan","Forecast","Actual"]),transferBalance=new Map(),transferPairs=new Map(),movementLedger=new Map(),exitShares=new Map();
for(const r of odMovements.slice(1)){
  const scenario=r[mi.Scenario],type=r[mi["Movement Type"]],date=new Date(r[mi.Month]),signed=Number(r[mi["Signed FTE"]]),enr=Number(r[mi["Transformation Social Cost (ENR)"]]);
  if(!odFiscalYears.has(r[mi["Fiscal Year"]]))throw Error(`Unexpected OD movement fiscal year ${r[mi["Fiscal Year"]]}`);if(!odScenarios.has(scenario))throw Error(`Unexpected OD movement scenario ${scenario}`);if(scenario==="Actual"&&date>new Date(2026,7,31))throw Error("Actual OD movement after August 2026");
  if(type==="Natural Attrition"||type==="Forced Exit"){if(r[mi["Exit Subtype"]]!==type)throw Error(`Invalid exit subtype ${r[mi["Movement ID"]]}`);if(signed>=0)throw Error(`Exit not negative ${r[mi["Movement ID"]]}`)}else if(r[mi["Exit Subtype"]])throw Error(`Non-exit has exit subtype ${r[mi["Movement ID"]]}`);
  if(type==="Forced Exit"){if(enr<=0)throw Error(`Forced Exit missing ENR ${r[mi["Movement ID"]]}`);const employerCost=Math.abs(Number(r[mi["Recurring Total People Cost Impact"]]));const factor=enr/(employerCost*9);if(factor<.899||factor>1.101)throw Error(`ENR outside country variation ${r[mi["Movement ID"]]}: ${factor}`)}else if(Math.abs(enr)>.01)throw Error(`ENR on non-forced movement ${r[mi["Movement ID"]]}`);
  if(Math.abs(Number(r[mi["Recurring Staff Cost Impact"]])+Number(r[mi["Recurring Employer Social Charges Impact"]])-Number(r[mi["Recurring Total People Cost Impact"]]))>.01)throw Error(`OD movement recurring cost reconciliation ${r[mi["Movement ID"]]}`);if(Math.abs(Number(r[mi["Recurring Total People Cost Impact"]])+enr-Number(r[mi["Total Cash Cost Impact Including ENR"]]))>.01)throw Error(`OD movement cash cost reconciliation ${r[mi["Movement ID"]]}`);
  if(type==="Transfer In"||type==="Transfer Out"){const key=[scenario,monthKey(date)].join("|");transferBalance.set(key,(transferBalance.get(key)||0)+signed);const pair=r[mi["Transfer Pair ID"]];if(!pair)throw Error("Transfer missing pair ID");transferPairs.set(pair,(transferPairs.get(pair)||0)+signed)}
  const key=[scenario,monthKey(date),r[mi["Legal Entity"]],r[mi.Function]].join("|"),item=movementLedger.get(key)||{hire:0,natural:0,forced:0,transferIn:0,transferOut:0,enr:0};if(type==="Hire")item.hire+=Math.abs(signed);if(type==="Natural Attrition")item.natural+=Math.abs(signed);if(type==="Forced Exit")item.forced+=Math.abs(signed);if(type==="Transfer In")item.transferIn+=Math.abs(signed);if(type==="Transfer Out")item.transferOut+=Math.abs(signed);item.enr+=enr;movementLedger.set(key,item);
  if(type==="Natural Attrition"||type==="Forced Exit"){const shareKey=[scenario,r[mi.Function]].join("|"),share=exitShares.get(shareKey)||{total:0,forced:0};share.total+=Math.abs(signed);if(type==="Forced Exit")share.forced+=Math.abs(signed);exitShares.set(shareKey,share)}
}
for(const [key,value] of transferBalance)if(Math.abs(value)>.0001)throw Error(`Transfer group imbalance ${key}: ${value}`);for(const [key,value] of transferPairs)if(Math.abs(value)>.0001)throw Error(`Transfer pair imbalance ${key}: ${value}`);
const monthlyCoverage=new Set(),monthlyKeys=new Set(),odLedger=new Map(),odRecurringCumulative=new Map(),odNetCumulative=new Map(),functionMonth=new Map();
for(const r of odMonthly.slice(1)){
  const date=new Date(r[oi.Month]),fy=r[oi["Fiscal Year"]],scenario=r[oi.Scenario],key=[scenario,monthKey(date),r[oi["Legal Entity"]],r[oi.Function]].join("|");
  if(monthlyKeys.has(key))throw Error(`Duplicate OD monthly row ${key}`);monthlyKeys.add(key);if(!(odFiscalYears.has(fy)||(scenario==="Baseline"&&fy==="FY25/26"&&monthKey(date)==="2026-06")))throw Error(`Unexpected OD monthly fiscal year ${fy}`);if(odFiscalYears.has(fy))monthlyCoverage.add(fy);if(!odScenarios.has(scenario))throw Error(`Unexpected OD monthly scenario ${scenario}`);if(scenario==="Actual"&&date>new Date(2026,7,31))throw Error("Actual OD monthly row after August 2026");if(scenario==="Forecast"&&date<new Date(2026,8,1))throw Error("Forecast OD monthly row before September 2026");
  const signed=Number(r[oi["Hire FTE"]])-Number(r[oi["Total Exit FTE"]])+Number(r[oi["Transfer In FTE"]])-Number(r[oi["Transfer Out FTE"]]);if(Math.abs(Number(r[oi["Natural Attrition FTE"]])+Number(r[oi["Forced Exit FTE"]])-Number(r[oi["Total Exit FTE"]]))>.0001||Math.abs(signed-Number(r[oi["Signed Movements FTE"]]))>.0001||Math.abs(Number(r[oi["Opening FTE"]])+signed-Number(r[oi["Closing FTE"]]))>.0001)throw Error(`OD FTE reconciliation ${key}`);
  if(Math.abs(Number(r[oi["Recurring Staff Cost"]])+Number(r[oi["Recurring Employer Social Charges"]])-Number(r[oi["Recurring Total People Cost"]]))>.01)throw Error(`OD monthly recurring cost reconciliation ${key}`);if(Math.abs(Number(r[oi["Recurring Total People Cost"]])+Number(r[oi["Transformation Social Cost (ENR)"]])-Number(r[oi["Total Cash Cost Including ENR"]]))>.01)throw Error(`OD monthly cash cost reconciliation ${key}`);if(Math.abs(Number(r[oi["Baseline Recurring Total People Cost"]])-Number(r[oi["Recurring Total People Cost"]])-Number(r[oi["Recurring Savings vs Baseline"]]))>.01)throw Error(`OD monthly recurring savings reconciliation ${key}`);if(Math.abs(Number(r[oi["Recurring Savings vs Baseline"]])-Number(r[oi["Transformation Social Cost (ENR)"]])-Number(r[oi["Net Savings After ENR"]]))>.01)throw Error(`OD monthly net savings reconciliation ${key}`);
  const chainKey=[scenario,r[oi["Legal Entity"]],r[oi.Function]].join("|"),previous=odLedger.get(chainKey);if(previous&&date>previous.date&&Math.abs(Number(r[oi["Opening FTE"]])-previous.closing)>.0001)throw Error(`OD opening/closing continuity ${key}`);odLedger.set(chainKey,{date,closing:Number(r[oi["Closing FTE"]])});const previousRecurring=odRecurringCumulative.get(chainKey);if(previousRecurring!=null&&Math.abs(previousRecurring+Number(r[oi["Recurring Savings vs Baseline"]])-Number(r[oi["Cumulative Recurring Savings"]]))>.01)throw Error(`OD cumulative recurring reconciliation ${key}`);odRecurringCumulative.set(chainKey,Number(r[oi["Cumulative Recurring Savings"]]));const previousNet=odNetCumulative.get(chainKey);if(previousNet!=null&&Math.abs(previousNet+Number(r[oi["Net Savings After ENR"]])-Number(r[oi["Cumulative Net Savings"]]))>.01)throw Error(`OD cumulative net reconciliation ${key}`);odNetCumulative.set(chainKey,Number(r[oi["Cumulative Net Savings"]]));
  const movements=movementLedger.get(key)||{hire:0,natural:0,forced:0,transferIn:0,transferOut:0,enr:0};if(Math.abs(movements.hire-Number(r[oi["Hire FTE"]]))>.0001||Math.abs(movements.natural-Number(r[oi["Natural Attrition FTE"]]))>.0001||Math.abs(movements.forced-Number(r[oi["Forced Exit FTE"]]))>.0001||Math.abs(movements.transferIn-Number(r[oi["Transfer In FTE"]]))>.0001||Math.abs(movements.transferOut-Number(r[oi["Transfer Out FTE"]]))>.0001||Math.abs(movements.enr-Number(r[oi["Transformation Social Cost (ENR)"]]))>.01)throw Error(`OD movement-to-ledger reconciliation ${key}`);
  const aggregateKey=[scenario,monthKey(date),r[oi.Function]].join("|"),aggregate=functionMonth.get(aggregateKey)||{fte:0,staff:0,social:0,enr:0,hire:0};aggregate.fte+=Number(r[oi["Closing FTE"]]);aggregate.staff+=Number(r[oi["Recurring Staff Cost"]]);aggregate.social+=Number(r[oi["Recurring Employer Social Charges"]]);aggregate.enr+=Number(r[oi["Transformation Social Cost (ENR)"]]);aggregate.hire+=Number(r[oi["Hire FTE"]]);functionMonth.set(aggregateKey,aggregate);
}
for(const entity of entities)for(const fn of functions){const actual=odMonthly.slice(1).filter(r=>r[oi.Scenario]==="Actual"&&r[oi["Legal Entity"]]===entity&&r[oi.Function]===fn).sort((a,b)=>new Date(a[oi.Month])-new Date(b[oi.Month])),forecast=odMonthly.slice(1).filter(r=>r[oi.Scenario]==="Forecast"&&r[oi["Legal Entity"]]===entity&&r[oi.Function]===fn).sort((a,b)=>new Date(a[oi.Month])-new Date(b[oi.Month]));if(actual.length&&forecast.length){if(Math.abs(Number(actual.at(-1)[oi["Closing FTE"]])-Number(forecast[0][oi["Opening FTE"]]))>.0001)throw Error(`Actual/Forecast OD continuity ${entity}/${fn}`);if(Math.abs(Number(actual.at(-1)[oi["Cumulative Recurring Savings"]])+Number(forecast[0][oi["Recurring Savings vs Baseline"]])-Number(forecast[0][oi["Cumulative Recurring Savings"]]))>.01)throw Error(`Actual/Forecast recurring continuity ${entity}/${fn}`);if(Math.abs(Number(actual.at(-1)[oi["Cumulative Net Savings"]])+Number(forecast[0][oi["Net Savings After ENR"]])-Number(forecast[0][oi["Cumulative Net Savings"]]))>.01)throw Error(`Actual/Forecast net continuity ${entity}/${fn}`)}}
const value=(scenario,month,fn,field)=>functionMonth.get([scenario,month,fn].join("|"))?.[field]||0,group=(scenario,month,field)=>functions.reduce((sum,fn)=>sum+value(scenario,month,fn,field),0),baselineFte=Object.fromEntries(functions.map(fn=>[fn,value("Baseline","2026-06",fn,"fte")])),planFinal={"D&T":Math.round(baselineFte["D&T"]*1.02),Finance:Math.round(baselineFte.Finance*.50),HR:Math.round(baselineFte.HR*.95),Marketing:Math.round(baselineFte.Marketing*.975),Sales:Math.round(baselineFte.Sales*.975)},baselineGroup=Object.values(baselineFte).reduce((sum,n)=>sum+n,0);planFinal.Supply=Math.round(baselineGroup*.90)-Object.values(planFinal).reduce((sum,n)=>sum+n,0);
for(const fn of functions)if(Math.abs(value("Plan","2029-06",fn,"fte")-planFinal[fn])>1)throw Error(`Plan final target ${fn}: ${value("Plan","2029-06",fn,"fte")}/${planFinal[fn]}`);for(const [month,target] of [["2027-06",.97],["2028-06",.93],["2029-06",.90]])if(Math.abs(group("Plan",month,"fte")-Math.round(baselineGroup*target))>1)throw Error(`Plan group milestone ${month}: ${group("Plan",month,"fte")}/${Math.round(baselineGroup*target)}`);
for(const scenario of ["Plan","Budget","Forecast"])for(const fn of functions){const exits=exitShares.get([scenario,fn].join("|"))||{total:0,forced:0},target=fn==="Finance"?.95:.30;if(exits.total&&Math.abs(exits.forced/exits.total-target)>.015)throw Error(`Forced exit share ${scenario}/${fn}: ${exits.forced/exits.total}`)}
const dtBaselineStaff=value("Baseline","2026-06","D&T","staff"),dtFinalStaff=value("Plan","2029-06","D&T","staff");if(Math.abs(value("Plan","2029-06","D&T","fte")/baselineFte["D&T"]-1.02)>.001)throw Error("D&T final FTE target");if(Math.abs(dtFinalStaff/dtBaselineStaff-.90)>.001)throw Error(`D&T final staff cost target ${dtFinalStaff/dtBaselineStaff}`);
for(const fn of functions.filter(fn=>fn!=="D&T")){const fteRatio=value("Plan","2029-06",fn,"fte")/baselineFte[fn],staffRatio=value("Plan","2029-06",fn,"staff")/value("Baseline","2026-06",fn,"staff");if(Math.abs(fteRatio-staffRatio)>.002)throw Error(`Staff cost does not follow FTE ${fn}: ${staffRatio}/${fteRatio}`)}for(const fn of functions){if(value("Plan","2029-06",fn,"social")>=value("Baseline","2026-06",fn,"social"))throw Error(`Recurring social charges did not decline ${fn}`)}
const totalHires=scenario=>functions.reduce((sum,fn)=>sum+Array.from(functionMonth.entries()).filter(([key])=>key.startsWith(`${scenario}|`)&&key.endsWith(`|${fn}`)).reduce((sub,[,item])=>sub+item.hire,0),0),dtHires=scenario=>Array.from(functionMonth.entries()).filter(([key])=>key.startsWith(`${scenario}|`)&&key.endsWith("|D&T")).reduce((sum,[,item])=>sum+item.hire,0);for(const scenario of ["Budget","Plan","Forecast"])if(totalHires(scenario)-dtHires(scenario)>1)throw Error(`Non-D&T recruitment not frozen ${scenario}`);
if(group("Budget","2029-06","fte")<=group("Plan","2029-06","fte"))throw Error("Budget is not behind Plan");if(group("Forecast","2029-06","fte")===group("Plan","2029-06","fte")||Math.abs(group("Forecast","2029-06","fte")-group("Plan","2029-06","fte"))>25)throw Error("Forecast is not close but distinct from Plan");
for(const fy of odFiscalYears)if(!monthlyCoverage.has(fy))throw Error(`Missing OD fiscal year ${fy}`);for(const scenario of ["Baseline","Budget","Plan"])for(const fy of odFiscalYears)if(!odMonthly.slice(1).some(r=>r[oi["Fiscal Year"]]===fy&&r[oi.Scenario]===scenario))throw Error(`Missing OD coverage ${scenario}/${fy}`);if(!odMonthly.slice(1).some(r=>r[oi.Scenario]==="Actual"&&monthKey(r[oi.Month])==="2026-08")||!odMonthly.slice(1).some(r=>r[oi.Scenario]==="Forecast"&&monthKey(r[oi.Month])==="2029-06"))throw Error("Incomplete Actual/Forecast OD coverage");
const dictionaryText=JSON.stringify(dictionary);for(const term of ["Transformation Social Cost","Natural Attrition","Forced Exit","Cumulative Net Savings"])if(!dictionaryText.includes(term))throw Error(`Data Dictionary missing ${term}`);const logText=JSON.stringify(log);for(const term of ["30%/70%/100%","nine months","D&T +2% final FTE"])if(!logText.includes(term))throw Error(`Generation Log missing ${term}`);
const text=JSON.stringify({mapping,baseline,budget,monthly,catalog,history,odMovements,odMonthly,log});for(const term of ["Bonduelle","F4P","GELT","Control Tower","Delivery Board","Marco","Guillaume"])if(text.toLowerCase().includes(term.toLowerCase()))throw Error(`Forbidden ${term}`);
const metrics={baselineGroupFte:baselineGroup,planMilestones:{"2027-06":group("Plan","2027-06","fte"),"2028-06":group("Plan","2028-06","fte"),"2029-06":group("Plan","2029-06","fte")},planFinalFte:Object.fromEntries(functions.map(fn=>[fn,value("Plan","2029-06",fn,"fte")])),planFinalFteChangePct:Object.fromEntries(functions.map(fn=>[fn,+((value("Plan","2029-06",fn,"fte")/baselineFte[fn]-1)*100).toFixed(3)])),planFinalGroupChangePct:+((group("Plan","2029-06","fte")/baselineGroup-1)*100).toFixed(3),dtFinalStaffCostChangePct:+((dtFinalStaff/dtBaselineStaff-1)*100).toFixed(3),budgetFinalGroupFte:group("Budget","2029-06","fte"),forecastFinalGroupFte:group("Forecast","2029-06","fte"),forcedExitShares:Object.fromEntries(functions.map(fn=>{const x=exitShares.get(`Plan|${fn}`)||{total:0,forced:0};return[fn,+(x.forced/x.total*100).toFixed(3)]}))};
console.log(JSON.stringify({sheets:w.SheetNames,budgetRows:budget.length-6,monthlyRows:monthly.length-1,kpiRows:catalog.length-1,kpiHistoryRows:history.length-1,odMovementRows:odMovements.length-1,odMonthlyRows:odMonthly.length-1,odFiscalYears:[...monthlyCoverage],traceRows:log.length-1,metrics}));
